doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            oysterpro:
                url: '%env(resolve:OYSTERPRO_DATABASE_URL)%'
        default_connection: default

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                #auto_generate_proxy_classes: true
                #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                #auto_mapping: true
                mappings:
                    SonataUserBundle: ~
                    ASC:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Asc'
                        prefix: 'App\Entity\Asc'
                        alias: Asc
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
            oysterpro:
                connection: oysterpro
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Oysterpro'
                        prefix: 'App\Entity\Oysterpro'
                        alias: Oysterpro

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
