sonata_admin:
    title: "Sonata Admin"
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
services:
    admin.parc:
        class: App\Admin\ParcAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Parc,
                  manager_type: orm,
                  label: Parc,
              }
    admin.stock:
        class: App\Admin\StockAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Stock\Stock,
                  manager_type: orm,
                  label: Stock,
                  group: Stockage,
              }
    admin.articles:
        class: App\Admin\ArticlesAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Articles,
                  manager_type: orm,
                  label: Article,
              }
    admin.corde:
        class: App\Admin\CordeAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Conteneur\Corde,
                  manager_type: orm,
                  label: Corde,
                  group: Conteneur,
              }
    admin.fruit.de.mer:
        class: App\Admin\FruitDeMerAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\FruitDeMer,
                  manager_type: orm,
                  label: FruitDeMer,
              }
    admin.lanterne:
        class: App\Admin\LanterneAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Conteneur\Lanterne,
                  manager_type: orm,
                  label: Lanterne,
                  group: Conteneur,
              }
    admin.poche:
        class: App\Admin\PocheAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Conteneur\Poche,
                  manager_type: orm,
                  label: Poche,
                  group: Conteneur,
              }
    admin.phase:
        class: App\Admin\PhaseAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\LifeProcess\Phase,
                  manager_type: orm,
                  label: Phase,
                  group: LifeProcess,
              }
    admin.processus:
        class: App\Admin\ProcessusAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\LifeProcess\Processus,
                  manager_type: orm,
                  label: Processus,
                  group: LifeProcess,
              }
    admin.cycle:
        class: App\Admin\CycleAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\LifeProcess\Cycle,
                  manager_type: orm,
                  label: Cycle,
                  group: LifeProcess,
              }
    admin.filiere:
        class: App\Admin\FiliereAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\FiliereComposite\Filiere,
                  manager_type: orm,
                  label: Filiere,
                  group: Composants Filiere,
              }
    admin.segment:
        class: App\Admin\SegmentAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\FiliereComposite\Segment,
                  manager_type: orm,
                  label: Segment,
                  group: Composants Filiere,
              }
    admin.flotteur:
        class: App\Admin\FlotteurAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\FiliereComposite\Flotteur,
                  manager_type: orm,
                  label: Flotteur,
                  group: Composants Filiere,
              }
    admin.emplacement:
        class: App\Admin\EmplacementAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\FiliereComposite\Emplacement,
                  manager_type: orm,
                  label: Emplacement,
                  group: Composants Filiere,
              }
    admin.flotteur_segment:
        class: App\Admin\FlotteurSegmentAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\FiliereComposite\FlotteurSegment,
                  manager_type: orm,
                  label: FlotteurSegment,
                  group: Composants Filiere,
              }
    admin.stock.article:
        class: App\Admin\StockArticleAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Stock\StockArticle,
                  manager_type: orm,
                  label: StockArticle,
                  group: Stockage,
              }
    admin.stock.corde:
        class: App\Admin\StockCordeAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Stock\StockCorde,
                  manager_type: orm,
                  label: StockCorde,
                  group: Stockage,
              }
    admin.stock.lanterne:
        class: App\Admin\StockLanterneAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Stock\StockLanterne,
                  manager_type: orm,
                  label: StockLanterne,
                  group: Stockage,
              }
    admin.stock.poche:
        class: App\Admin\StockPocheAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Stock\StockPoche,
                  manager_type: orm,
                  label: StockPoche,
                  group: Stockage,
              }
    admin.alerte.vert:
        class: App\Admin\AlerteVertAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Alerte\AlerteVert,
                  manager_type: orm,
                  label: Alerte Vert,
                  group: Alerte,
              }
    admin.alerte.jaune:
        class: App\Admin\AlerteJauneAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Alerte\AlerteJaune,
                  manager_type: orm,
                  label: Alerte Jaune,
                  group: Alerte,
              }
    admin.alerte.rouge:
        class: App\Admin\AlerteRougeAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Asc\Alerte\AlerteRouge,
                  manager_type: orm,
                  label: Alerte Rouge,
                  group: Alerte,
              }
