version: "3.8"
services:
    database:
        image: mysql:5.7
        container_name: db_fmb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'mourad'
            MYSQL_DATABASE: fmb
        ports:
            - '3307:3306'
        networks:
            - dev
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_fmb
        restart: always
        depends_on:
            - database
        ports:
            - 8082:80
        environment:
            PMA_HOST: database
        networks:
            - dev
    maildev:
        image: maildev/maildev
        container_name: maildev_fmb
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8083:80"
        restart: always
        networks:
            - dev
    www:
        build: .
        container_name: www_fmb
        ports:
          - "2514:80"
        volumes:
            - ./conf/:/etc/apache2/sites-enabled
            - ./:/var/www/fmb
        restart: always
        networks:
            - dev
networks:
    dev:

volumes:
    db-data:
