<?php

namespace OysterPro28Bundle\Repository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

use Doctrine\ORM\EntityRepository;

/**
 * FiliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlotteurRepository extends NestedTreeRepository
{

}
