<?php

namespace App\Repository;

use App\Entity\StocksArticlesSnVirtuel;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * StocksArticlesSnVirtuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StocksArticlesSnVirtuelRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, StocksArticlesSnVirtuel::class);
    }

    // /**
    //  * @return Carousel[] Returns an array of Carousel objects
    //  */
    /*
    public function findByExampleField($value)
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.exampleField = :val')
            ->setParameter('val', $value)
            ->orderBy('c.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }
    */

    /*
    public function findOneBySomeField($value): ?Carousel
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.exampleField = :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
    */
    public function getSAS($refStocksArticles, $numeroSerie)
    {
        $qb = $this->createQueryBuilder('sas');
        $qb->where('sas.refStockArticle = ?1')
            ->setParameter(1, $refStocksArticles)
            ->andWhere('sas.numeroSerie = ?2')
            ->setParameter(2, $numeroSerie);

        return $qb->getQuery()->getOneOrNullResult();

    }
}
