version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces/asc:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    depends_on:
      - db

    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003

  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mourad
      MYSQL_DATABASE: asc
      MYSQL_USER: mourad
      MYSQL_PASSWORD: mourad
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mysql-data: