# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: "fr"
    app.url: "%env(APP_URL)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ParcCacheService:
        arguments:
            $parcRepository: '@App\Repository\ParcRepository'
            $cache: "@cache.app"
            $mouleCalculator: '@App\Service\MouleCalculator'

    App\EventListener\ParcCacheInvalidator:
        arguments:
            $parcCacheService: '@App\Service\ParcCacheService'
        tags:
            - { name: doctrine.orm.entity_listener }

    admin.parc:
        class: App\Admin\ParcAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Parc,
                  manager_type: orm,
                  label: Parc,
              }
    admin.filiere:
        class: App\Admin\FiliereAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Filiere,
                  manager_type: orm,
                  label: Filiere,
                  group: Structure d'élevage,
              }
    admin.segment:
        class: App\Admin\SegmentAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Segment,
                  manager_type: orm,
                  label: Segment,
                  group: Structure d'élevage,
              }
    admin.flotteur:
        class: App\Admin\FlotteurAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Flotteur,
                  manager_type: orm,
                  label: Flotteur,
                  group: Structure d'élevage,
              }
    admin.flotteur.segment:
        class: App\Admin\FlotteurSegmentAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\FlotteurSegment,
                  manager_type: orm,
                  label: FlotteurSegment,
                  group: Structure d'élevage,
              }

    admin.articles:
        class: App\Admin\ArticlesAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Articles,
                  controller: ~,
                  manager_type: orm,
                  group: Espece,
                  label: Articles,
              }

    admin.corde:
        class: App\Admin\CordeAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Corde,
                  controller: ~,
                  manager_type: orm,
                  group: Matériel d'élevage,
                  label: Corde,
              }

    admin.stock_corde:
        class: App\Admin\StockCordeAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\StockCorde,
                  controller: ~,
                  manager_type: orm,
                  group: Matériel d'élevage,
                  label: StockCorde,
              }

    admin.fruit_de_mer:
        class: App\Admin\FruitDeMerAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\FruitDeMer,
                  controller: ~,
                  manager_type: orm,
                  group: Espece,
                  label: Espece,
              }

    admin.stock:
        class: App\Admin\StockAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Stock,
                  controller: ~,
                  manager_type: orm,
                  group: Stocks Tous parcs,
                  label: Stock,
              }

    admin.stock_article:
        class: App\Admin\StockArticleAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\StockArticle,
                  controller: ~,
                  manager_type: orm,
                  group: Espece,
                  label: StockArticle,
              }

    admin.stock_article_sn:
        class: App\Admin\StockArticleSnAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\StockArticleSn,
                  controller: ~,
                  manager_type: orm,
                  group: Espece,
                  label: StockArticleSn,
              }

    admin.emplacement:
        class: App\Admin\EmplacementAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Emplacement,
                  controller: ~,
                  manager_type: orm,
                  group: Structure d'élevage,
                  label: Emplacement,
              }

    admin.lanterne:
        class: App\Admin\LanterneAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Lanterne,
                  controller: ~,
                  manager_type: orm,
                  group: admin,
                  label: Lanterne,
              }

    admin.phase:
        class: App\Admin\PhaseAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Phase,
                  controller: ~,
                  manager_type: orm,
                  group: admin,
                  label: Phase,
              }

    admin.processus:
        class: App\Admin\ProcessusAdmin
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\Processus,
                  controller: ~,
                  manager_type: orm,
                  group: admin,
                  label: Processus,
              }

    admin.user:
        class: App\Admin\UserAdmin
        arguments:
            - App\Entity\User
        tags:
            - {
                  name: sonata.admin,
                  model_class: App\Entity\User,
                  controller: ~,
                  manager_type: orm,
                  group: admin,
                  label: User,
              }
