name: Deploy to FTP

on:
  workflow_run:
    workflows: ["Install Dependencies"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Modifier selon ton projet
          server-dir: "/www/"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.bfg-report*/**
            **/var/cache/**