name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Create .env.local file for MySQL
        run: |
          echo "DATABASE_URL=\"mysql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}/${{ secrets.DB_NAME }}\"" > .env.local
          echo "APP_ENV=dev" >> .env.local
          echo "APP_SECRET=\"${{ secrets.APP_SECRET }}\"" >> .env.local
          echo "MESSENGER_TRANSPORT_DSN=\"doctrine://default?auto_setup=0\"" >> .env.local
          # OYSTERPRO_DATABASE_URL n'est pas défini en production

      - name: Install PHP dependencies
        run: composer install --optimize-autoloader --no-scripts

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Node.js dependencies with Yarn
        run: yarn install
        
      - name: Create necessary directories and SQLite database
        run: |
          mkdir -p var
          touch var/data.db
          chmod -R 777 var
          echo "DATABASE_URL=sqlite://%kernel.project_dir%/var/data.db" >> .env

      - name: Verify SQLite database file exists
        run: ls -la var

      - name: assets:install
        run: DATABASE_URL=sqlite://%kernel.project_dir%/var/data.db php bin/console assets:install --symlink --no-debug

      - name: Remove SQLite database configuration
        run: sed -i '/DATABASE_URL=sqlite/d' .env

      - name: Build assets with Yarn
        run: yarn dev

    outputs:
      success: true
