name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install PHP dependencies
        run: composer install --optimize-autoloader --no-scripts

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Node.js dependencies with Yarn
        run: yarn install

    outputs:
      success: true

